# Generated by Django 3.0.7 on 2020-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo_upload',
            old_name='upload',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='photo_upload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
